# Autogenerated Lambda test
# Template: PY

import os
import pytest

from unittest import mock
from calculate import handler


@pytest.fixture()
def mock_env_vars_calculateCase1():
    with mock.patch.dict(os.environ, {
        "OPERATION": "multiply"
    }):
        yield


def test_calculateCase1(mock_env_vars_calculateCase1):
    event = {
        "a": 2,
        "b": 3
    }

    result = handler(event, [])

    assert result == 6


@pytest.fixture()
def mock_env_vars_calculateCase2():
    with mock.patch.dict(os.environ, {
        "OPERATION": "add"
    }):
        yield


def test_calculateCase2(mock_env_vars_calculateCase2):
    event = {
        "a": 2,
        "b": 3
    }

    result = handler(event, [])

    assert result == 5
