# Autogenerated Lambda test
# Template: PY

import os
import pytest

from unittest import mock
from math import handler


@pytest.fixture(autouse=True)
def mock_env_vars():
    with mock.patch.dict(os.environ, {
        "OPERATION" : "multiply"
        }):
            yield

def mathCase1 ():
    event = {
    "a": 2,     "b": 2  }

    result = handler(event, [])

    assert result == 4

