// Autogenerated Lambda test
// Template: JS

import * as math from "../math";

describe("math", () => {
  beforeAll(() => {
      process.env.OPERATION = "multiply";
  });

  test("mathCase1", async () => {
    const event = {
      "a": 2,       "b": 2    };
    const result = await math.handler(event);

    expect(result).toEqual(4);
  });
});