// Autogenerated Serverless test
// Template: JS

import * as math from "../math";

describe("math", () => {
  beforeAll(() => {
    process.env.OPERATION = "multiply";
  });

  test("case", async () => {
    const result = await math.handler();

    expect(result).toMatchObject({ statusCode: 200 });
  });
});