// Autogenerated Lambda test
// Template: JS

import * as calculate from "../calculate";

describe("calculate", () => {
  test("calculateCase1", async () => {
    process.env.OPERATION = "multiply";

    const event = {
      a: 2,
      b: 3    
    };

    const result = await calculate.handler(event);

    expect(result).toEqual(6);
  });

  test("calculateCase2", async () => {
    process.env.OPERATION = "add";

    const event = {
      a: 2,
      b: 3    
    };

    const result = await calculate.handler(event);

    expect(result).toEqual(5);
  });
});
