service: demo-service

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  environment:
    HELLO: ${env:HELLO}
    API_URL: ${env:API_URL}

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  hello:
    handler: hello.handler
    events:
      - http:
          path: hello
          method: get

  activity:
    handler: activity.handler
    events:
      - http:
          path: activity
          method: get

  calculate:
    handler: calculate.handler
    events:
      - http:
          path: activity
          method: get
