service: demo-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    HELLO: ${env:HELLO}
    API_URL: ${env:API_URL}

plugins:
  - serverless-bundle
  - serverless-offline

functions:
  hello:
    handler: hello.handler
    events:
      - http:
          path: hello
          method: get

  activity:
    handler: activity.handler
    events:
      - http:
          path: activity
          method: get
  
  math:
    handler: math.handler
    events:
      - http:
          path: activity
          method: get
